const INVESTIGATION_STATES = {
  CREATED: "CREATED",
  COLLECTING_EVIDENCE: "COLLECTING_EVIDENCE",
  EVIDENCE_READY: "EVIDENCE_READY",
  RECONCILING: "RECONCILING",
  RECONCILED: "RECONCILED",
  AI_ANALYSIS: "AI_ANALYSIS",
  COMPLETED: "COMPLETED",
  FAILED: "FAILED",
};

const stateTransitions = {
  CREATED: [
    INVESTIGATION_STATES.COLLECTING_EVIDENCE,
    INVESTIGATION_STATES.FAILED,
  ],

  COLLECTING_EVIDENCE: [
    INVESTIGATION_STATES.EVIDENCE_READY,
    INVESTIGATION_STATES.FAILED,
  ],

  EVIDENCE_READY: [
    INVESTIGATION_STATES.RECONCILING,
    INVESTIGATION_STATES.FAILED,
  ],

  RECONCILING: [
    INVESTIGATION_STATES.RECONCILED,
    INVESTIGATION_STATES.FAILED,
  ],

  RECONCILED: [
    INVESTIGATION_STATES.AI_ANALYSIS,
    INVESTIGATION_STATES.COMPLETED,
    INVESTIGATION_STATES.FAILED,
  ],

  AI_ANALYSIS: [
    INVESTIGATION_STATES.COMPLETED,
    INVESTIGATION_STATES.FAILED,
  ],

  COMPLETED: [],

  FAILED: [],
};

const canTransition = (from, to) => {
  return stateTransitions[from]?.includes(to) || false;
};

const getNextStates = (state) => {
  return stateTransitions[state] || [];
};

export {
  INVESTIGATION_STATES,
  canTransition,
  getNextStates,
};